name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle 9.3.1
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '9.3.1'

    # Chạy lệnh biên dịch thuần túy (Bỏ qua toàn bộ các lớp test và xác thực)
    - name: Build Debug APK
      run: gradle :app:assembleDebug --no-configuration-cache -x test -x lint

    # Gom chính xác file APK găm lên mục Summary cho bạn tải về máy tính
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SieuDongBangAPK
        path: |
          **/build/outputs/apk/debug/*.apk
